
//  Created by Евгений Никитин on 15.04.2020.
//  Copyright © 2020 Evel-Devel. All rights reserved.

import Foundation

class TypesOfDataSet {
    static func getQuestions() -> [Question] {
        return [
            Question(question: "Тип данных, отвечающий за хранение отдельных Unicode-символов",
                     image: "screen",
                     optionA: "Bool",
                     optionB: "Float",
                     optionC: "Character",
                     optionD: "String",
                     correctAnswer: 3,
                     questionId: 1,
                     helpText: "Первый"),
            
            Question(question: "Тип данных, отвечающий за хранение произвольной текстовой информации",
                     image: "screen2",
                     optionA: "Float",
                     optionB: "String",
                     optionC: "Character",
                     optionD: "Bool",
                     correctAnswer: 2,
                     questionId: 2,
                     helpText: "Второй"),
            
            Question(question: "Какой тип данных хранит числа, не содержащие дробной части (например 42 или -23)?",
                     image: "",
                     optionA: "UInt",
                     optionB: "Int",
                     optionC: "Float",
                     optionD: "Double",
                     correctAnswer: 2,
                     questionId: 3,
                     helpText: "Третий"),
            
            Question(question: "Все типы в Swift пишутся с ...",
                     image: "",
                     optionA: "Строчной буквы",
                     optionB: "Греческой цифры",
                     optionC: "Заглавной буквы",
                     optionD: "Текущей даты",
                     correctAnswer: 3,
                     questionId: 4,
                     helpText: ""),
            
            Question(question: "Как получить доступ к минимальному и максимальному значению каждого типа целого числа?",
                     image: "screen2",
                     optionA: "first и last",
                     optionB: "min и max",
                     optionC: "count",
                     optionD: "first и max",
                     correctAnswer: 2,
                     questionId: 5,
                     helpText: ""),
            
            Question(question: "Какой тип может хранить более длинные дробные числа?",
                     image: "",
                     optionA: "Double",
                     optionB: "Float",
                     optionC: "Character",
                     optionD: "String",
                     correctAnswer: 1,
                     questionId: 6,
                     helpText: ""),
            
            Question(question: "Какой тип хранит только положительные целые числа?",
                     image: "",
                     optionA: "Int",
                     optionB: "Int64",
                     optionC: "UInt",
                     optionD: "Character",
                     correctAnswer: 3,
                     questionId: 7,
                     helpText: ""),
            
            Question(question: "Фиксированная последовательность символов, окруженная двойными кавычками",
                     image: "",
                     optionA: "Числовой литерал",
                     optionB: "Строковый литерал",
                     optionC: "Литерал",
                     optionD: "Натурал",
                     correctAnswer: 2,
                     questionId: 8,
                     helpText: ""),
            
            Question(question: "Фиксированная последовательность цифр, начинающаяся либо с цифры, либо с префиксного оператора «-» или «+»",
                     image: "",
                     optionA: "Оператор",
                     optionB: "Числовой литерал",
                     optionC: "Строковый литерал",
                     optionD: "Генерал",
                     correctAnswer: 2,
                     questionId: 9,
                     helpText: ""),
            
            Question(question: "Как можно объявлять тип данных?",
                     image: "",
                     optionA: "Внятно",
                     optionB: "Неявно",
                     optionC: "Явно или Неявно",
                     optionD: "Внятно или Явно",
                     correctAnswer: 3,
                     questionId: 10,
                     helpText: ""),
            
            Question(question: "Можно ли использовать переменную или константу, с явным типом данных, до ее инициализации?",
                     image: "",
                     optionA: "Можно",
                     optionB: "Нельзя",
                     optionC: "Не совсем",
                     optionD: "Только в день рождения",
                     correctAnswer: 2,
                     questionId: 11,
                     helpText: ""),
            
            Question(question: "Какой тип может хранить любое целое число в пределах от -2 147 483 648 до 2 147 483 647?",
                     image: "",
                     optionA: "Uint32",
                     optionB: "Decimal",
                     optionC: "Int32",
                     optionD: "Int64",
                     correctAnswer: 3,
                     questionId: 12,
                     helpText: ""),
            
            Question(question: "Если в коде не указать размер целого числа, каким оно будет?",
                     image: "",
                     optionA: "Согласно разрядности системы",
                     optionB: "32",
                     optionC: "64",
                     optionD: "128",
                     correctAnswer: 1,
                     questionId: 13,
                     helpText: ""),
            
            Question(question: "Как называется объявление переменной с присваиванием ей значения?",
                     image: "",
                     optionA: "Инаугурация",
                     optionB: "Возведение",
                     optionC: "Объявление",
                     optionD: "Инициализация",
                     correctAnswer: 4,
                     questionId: 14,
                     helpText: ""),
            
            Question(question: "Какую точность в десятичных цифрах имеет тип Double?",
                     image: "",
                     optionA: "15 десятичных цифр",
                     optionB: "6 десятичных цифр",
                     optionC: "12 десятичных цифр",
                     optionD: "18 десятичных цифр",
                     correctAnswer: 1,
                     questionId: 15,
                     helpText: ""),
            
            Question(question: "Какую точность в десятичных цифрах имеет тип Float?",
                     image: "",
                     optionA: "4 десятичных цифр",
                     optionB: "6 десятичных цифр",
                     optionC: "12 десятичных цифр",
                     optionD: "10 десятичных цифр",
                     correctAnswer: 2,
                     questionId: 16,
                     helpText: ""),
            
            Question(question: "Если равноценно использование обоих типов с плавающей точкой, использование какого предпочтительнее?",
                     image: "",
                     optionA: "Double",
                     optionB: "Float",
                     optionC: "Decimal",
                     optionD: "String",
                     correctAnswer: 1,
                     questionId: 17,
                     helpText: ""),
            
            Question(question: "Можете ли вы передать тип Int, если некоторая часть кода ожидает тип String?",
                     image: "",
                     optionA: "Да",
                     optionB: "Нет",
                     optionC: "В некоторых случаях",
                     optionD: "По настроению",
                     correctAnswer: 2,
                     questionId: 18,
                     helpText: ""),
            
            Question(question: "По сколько кавычек ставится при открытии и закрытии многострочного литерала?",
                     image: "",
                     optionA: "По 1",
                     optionB: "По 2",
                     optionC: "По 3",
                     optionD: "По 4",
                     correctAnswer: 3,
                     questionId: 19,
                     helpText: ""),
            
            Question(question: "Каким символом(ами) осуществляется перенос строки в многострочном строковом литерале?",
                     image: "",
                     optionA: "Звездочка",
                     optionB: "Обратный слеш",
                     optionC: "Нажимаем Enter",
                     optionD: "Тире",
                     correctAnswer: 2,
                     questionId: 20,
                     helpText: ""),
            
            Question(question: "Как можно инициализировать пустую строку?",
                     image: "",
                     optionA: "Пустые кавычки после =",
                     optionB: "= [String]",
                     optionC: "Первые два варианта",
                     optionD: "Оба варианта неверны",
                     correctAnswer: 1,
                     questionId: 21,
                     helpText: ""),
            
            Question(question: "Способ создать новое значение типа String из разных констант, переменных, литералов и выражений, включая их значения в строковый литерал",
                     image: "",
                     optionA: "Конкатенация",
                     optionB: "Интерполяция",
                     optionC: "Объединение строк",
                     optionD: "Вкрапление значений",
                     correctAnswer: 2,
                     questionId: 22,
                     helpText: ""),
            
            Question(question: "Каким образом можно добавить значение типа Character к переменной типа String?",
                     image: "",
                     optionA: "Комбинированные операторы",
                     optionB: "Конкатенация",
                     optionC: "Приведение типов",
                     optionD: "Используя String append",
                     correctAnswer: 4,
                     questionId: 23,
                     helpText: ""),
            
            Question(question: "Можно ли сравнивать две строки?",
                     image: "",
                     optionA: "Нет",
                     optionB: "Можно, только на равенство",
                     optionC: "Можно, только на неравенство",
                     optionD: "Можно, через операторы == и !=",
                     correctAnswer: 4,
                     questionId: 24,
                     helpText: ""),
            
            Question(question: "Что вернется, при сравнении двух String?",
                     image: "",
                     optionA: "Bool",
                     optionB: "String",
                     optionC: "Character",
                     optionD: "+ или -",
                     correctAnswer: 1,
                     questionId: 25,
                     helpText: "")
        ]
    }
}


