
//  Created by Евгений Никитин on 10.05.2020.
//  Copyright © 2020 Evel-Devel. All rights reserved.

import Foundation

class CollectionsSet {
    static func getQuestions() -> [Question] {
        return [
            Question(question: ["Сколько основных типов коллекций обеспечивает Swift?",
                                "Swift поддерживает именно столько основных типов коллекций",
                                "Какое количество типов коллекций поддерживается в Swift?"],
                     image: "",
                     optionA: "Два",
                     optionB: "Три",
                     optionC: "Четыре",
                     optionD: "Пять",
                     correctAnswer: 2,
                     questionId: 1,
                     helpText: "Swift обеспечивает три основных типа коллекций - это Массивы, Множества и Словари для хранения коллекций значений."),
            
            Question(question: ["Упорядоченная коллекция значений",
                                "Коллекция с упорядоченными значениями",
                                "Упорядоченные значения, объединенные в коллекцию"],
                     image: "",
                     optionA: "Массив",
                     optionB: "Словарь",
                     optionC: "Множество",
                     optionD: "Набор",
                     correctAnswer: 1,
                     questionId: 2,
                     helpText: "Массивы - это упорядоченные коллекции значений."),
            
            Question(question: ["Неупорядоченная коллекция уникальных значений",
                                "Уникальные значения, собранные в неупорядоченную коллекцию",
                                "Коллекция неупорядоченных уникальных значений"],
                     image: "",
                     optionA: "Массив",
                     optionB: "Множество",
                     optionC: "Словарь",
                     optionD: "Набор",
                     correctAnswer: 2,
                     questionId: 3,
                     helpText: "Множества - это неупорядоченные коллекции уникальных значений."),
            
            Question(question: ["Неупорядоченная коллекция, хранящая пары ключ-значение",
                                "Коллекция, хранящая неупорядоченные пары ключ-значение",
                                "Неупорядоченные пары ключ-значение хранятся именно в этой коллекции"],
                     image: "",
                     optionA: "Массив",
                     optionB: "Множество",
                     optionC: "Словарь",
                     optionD: "Набор",
                     correctAnswer: 3,
                     questionId: 4,
                     helpText: "Словари - это неупорядоченные коллекции, хранящие пары ключ-значение"),
            
            Question(question: ["Какой тип коллекции на изображении?",
                                "Укажите какой тип коллекции изображен на изображении?",
                                "На этом изображении именно этот тип коллекции"],
                     image: "Collections5",
                     optionA: "Массив",
                     optionB: "Множество",
                     optionC: "Набор",
                     optionD: "Словарь",
                     correctAnswer: 4,
                     questionId: 5,
                     helpText: "На изображении словарь, коллекция пар ключ-значение"),
            
            Question(question: ["Можем ли мы по ошибке вставить значение неверного типа в коллекцию?",
                                "Можем ли мы вставить значение неверного типа в массив?",
                                "Возможно ли вставить значение неверного типа в словарь? "],
                     image: "",
                     optionA: "Нет",
                     optionB: "Да",
                     optionC: "Да, через .append",
                     optionD: "Да, через оператор присваивания",
                     correctAnswer: 1,
                     questionId: 6,
                     helpText: "Массивам, множествам и словарям в Swift всегда понятно, какие типы значений и ключи они могут хранить. Это означает, что вы не можете по ошибке вставить неверное значение в коллекцию. Это также означает, что вы можете быть уверены в типах значений, которые вы получите из коллекции."),
            
            Question(question: ["Если массив или словарь присвоены переменной, можем ли мы его менять?",
                                "Можем ли мы изменять словарь или массив, если он присвоен переменной?",
                                "Будет ли массив изменяемым, если при создании мы присвоили его переменной?"],
                     image: "",
                     optionA: "Только удалять элементы",
                     optionB: "Только добавлять элементы",
                     optionC: "Да",
                     optionD: "Изменяются только массивы",
                     correctAnswer: 3,
                     questionId: 7,
                     helpText: "Когда вы создаете массив или словарь и присваиваете его переменной, то созданная коллекция будет изменяемой. Это означает, что вы можете изменить коллекцию после ее создания путем добавления, удаления, или изменения элементов этой коллекции. И наоборот, когда вы присвоите массив или словарь константе, то он будет неизменяемым, а его размер и содержимое не может быть изменено."),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 8,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 9,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 10,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 11,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 12,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 13,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 14,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 15,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 16,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 17,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 18,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 19,
                     helpText: ""),
            
            Question(question: ["",
                                "",
                                ""],
                     image: "",
                     optionA: "",
                     optionB: "",
                     optionC: "",
                     optionD: "",
                     correctAnswer: 1,
                     questionId: 20,
                     helpText: ""),
        ]
    }
}
